apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "filebeat.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "filebeat.fullname" . }}
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: {{ include "filebeat.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
